name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Android SDK and NDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            cmdline-tools;latest  
            build-tools;34.0.0
            ndk;25.1.8937393      
          accept-android-sdk-licenses: true

      - name: Install Buildozer
        run: |
          pip install buildozer cython==0.29.33

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/25.1.8937393
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/*.apk