name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: "3.10"

      - name: Install Buildozer and dependencies
        run: |
          pip install buildozer cython==0.29.33

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: app-debug.apk
          path: bin/*.apk  # Ensure the APK exists here